#!/usr/bin/env python3
"""Generate paper artifacts from the accuracy batch: a LaTeX results table, an
EER comparison bar chart, and DET curves -- all recomputed from the saved
embeddings with a single (zscore) prescale, so table and figures agree.

Run from bench/accuracy with system python3 (numpy + matplotlib):
    python3 make_paper_artifacts.py [--data /tmp/sable_paper] [--out ../../docs/papers]
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import datasets
import metrics
import sable_quant as sq

CELLS = [("lfw", "LFW"), ("calfw", "CALFW"), ("cplfw", "CPLFW")]
BACKBONES = [("faceres", "FaceRes"), ("arcface", "ArcFace")]
ENCODINGS = [
    ("float_cosine", "float cosine", lambda a, b: sq.score_float_cosine(a, b)),
    ("hamming_binary", "binary Hamming", lambda a, b: sq.score_hamming_binary(a, b)),
    ("thermo_l9", "thermometer L9", lambda a, b: sq.score_thermo(a, b, 9)),
]


PRESCALES = ["none", "tanh", "minmax", "zscore"]


def cell_rocs(data: Path, ds: str, bb: str):
    """Return ({enc_key: (eer, far, tar, prescale)}, n_pairs) for one cell.

    Each encoding is reported under its OWN best prescale (min EER across the
    four), the fair "deploy each at its best config" methodology. ROC stored is
    the one at that best prescale (used for the DET curves).
    """
    base = data / ds
    emb_a, emb_b, match = datasets.load_pairs_list(
        str(base / "pairs.txt"), str(base / f"{bb}.npz"))
    labels = match.astype(int)
    scaled = {}
    for ps in PRESCALES:
        a, stats = sq.prescale(emb_a, ps)
        b, _ = sq.prescale(emb_b, ps, stats)
        scaled[ps] = (a, b)
    out = {}
    for key, _label, fn in ENCODINGS:
        best = None
        for ps in PRESCALES:
            a, b = scaled[ps]
            far, tar, thr = metrics._roc(fn(a, b), labels)
            eer, _ = metrics._eer(far, tar, thr)
            if best is None or eer < best[0]:
                best = (eer, far, tar, ps)
        out[key] = best
    return out, len(labels)


def collect(data: Path):
    grid, npairs = {}, {}
    for ds, _ in CELLS:
        for bb, _ in BACKBONES:
            if (data / ds / f"{bb}.npz").exists():
                e, n = cell_rocs(data, ds, bb)
                grid[(ds, bb)] = e
                npairs[(ds, bb)] = n
                print(f"  {ds}/{bb} (n={n}): "
                      + "  ".join(f"{k}={v[0]*100:.2f}%[{v[3]}]" for k, v in e.items()))
    return grid, npairs


def write_latex(grid, npairs, out: Path):
    out.mkdir(parents=True, exist_ok=True)
    lines = [
        r"% Auto-generated by bench/accuracy/make_paper_artifacts.py",
        r"\begin{table}[t]", r"\centering",
        r"\caption{Verification EER (\%) by embedding backbone and matcher "
        r"encoding. Each encoding is reported under its best per-dimension "
        r"prescale; thermometer L9 uses the same 8\,bits/dim as binary Hamming. "
        r"$\Delta$ is the binary-Hamming penalty over float cosine. $N$ is the "
        r"number of usable pairs (FaceRes fails to detect many cross-pose CPLFW "
        r"faces). Sampled-pair protocol; relative gaps are the signal, not "
        r"absolute EERs.}",
        r"\label{tab:encoding-ablation}",
        r"\begin{tabular}{@{}llrcccc@{}}", r"\toprule",
        r"Dataset & Backbone & $N$ & Float & Binary & $\Delta$ & Thermo-L9 \\",
        r"\midrule",
    ]
    for ds, dlabel in CELLS:
        for bb, blabel in BACKBONES:
            if (ds, bb) not in grid:
                continue
            e = grid[(ds, bb)]
            fc = e["float_cosine"][0] * 100
            hb = e["hamming_binary"][0] * 100
            t9 = e["thermo_l9"][0] * 100
            lines.append(
                f"{dlabel} & {blabel} & {npairs[(ds, bb)]} & {fc:.2f} & {hb:.2f} & "
                f"$+{hb-fc:.2f}$ & {t9:.2f} \\\\")
        lines.append(r"\midrule" if ds != CELLS[-1][0] else r"\bottomrule")
    lines += [r"\end{tabular}", r"\end{table}", ""]
    (out / "encoding_results.tex").write_text("\n".join(lines))
    print(f"wrote {out/'encoding_results.tex'}")


def plot_eer_bars(grid, figs: Path):
    figs.mkdir(parents=True, exist_ok=True)
    cells = [(ds, bb) for ds, _ in CELLS for bb, _ in BACKBONES if (ds, bb) in grid]
    labels = [f"{d.upper()}\n{b}" for d, b in cells]
    x = np.arange(len(cells)); w = 0.26
    fig, ax = plt.subplots(figsize=(8, 3.4))
    for i, (key, lab, _) in enumerate(ENCODINGS):
        vals = [grid[c][key][0] * 100 for c in cells]
        ax.bar(x + (i - 1) * w, vals, w, label=lab)
    ax.set_ylabel("EER (%)")
    ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
    ax.legend(fontsize=8, ncol=3, loc="upper left")
    ax.grid(axis="y", alpha=0.3)
    ax.set_title("Matcher encoding effect on verification EER")
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / f"encoding_eer.{ext}", dpi=150)
    plt.close(fig)
    print(f"wrote {figs/'encoding_eer.pdf'}")


def plot_det(grid, figs: Path, cell=("cplfw", "faceres")):
    if cell not in grid:
        cell = next(iter(grid))
    fig, ax = plt.subplots(figsize=(4.2, 3.6))
    for key, lab, _ in ENCODINGS:
        eer, far, tar, _ps = grid[cell][key]
        fnr = 1 - tar
        m = far > 0
        ax.plot(far[m], fnr[m], label=f"{lab} (EER {eer*100:.1f}%)")
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlabel("False Accept Rate"); ax.set_ylabel("False Reject Rate")
    ax.set_title(f"DET — {cell[0].upper()}/{cell[1]}")
    ax.legend(fontsize=8); ax.grid(alpha=0.3, which="both")
    fig.tight_layout()
    name = f"det_{cell[0]}_{cell[1]}"
    for ext in ("pdf", "png"):
        fig.savefig(figs / f"{name}.{ext}", dpi=150)
    plt.close(fig)
    print(f"wrote {figs/(name+'.pdf')}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="/tmp/sable_paper")
    ap.add_argument("--out", default="../../docs/papers")
    args = ap.parse_args()
    data = Path(args.data)
    out = Path(args.out).resolve()
    figs = out / "figs"

    print("recomputing ROC/EER (best prescale per encoding)...")
    grid, npairs = collect(data)
    if not grid:
        raise SystemExit("no cells found")
    write_latex(grid, npairs, out)
    plot_eer_bars(grid, figs)
    plot_det(grid, figs, ("cplfw", "faceres"))
    plot_det(grid, figs, ("lfw", "faceres"))
    print("done.")


if __name__ == "__main__":
    main()
